/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserStats = IDL.Record({
  'referralCode' : IDL.Text,
  'coinBalance' : IDL.Int,
  'totalEarned' : IDL.Int,
  'referralCount' : IDL.Int,
  'dailyReadCount' : IDL.Int,
  'lastResetDate' : IDL.Int,
});
export const Time = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'bankAccountNumber' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'ifscCode' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'upiId' : IDL.Text,
  'bankAccountName' : IDL.Text,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'approveWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimReward' : IDL.Func([], [], []),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats))],
      ['query'],
    ),
  'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'getNews' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Article)], ['query']),
  'getReferralCode' : IDL.Func([], [IDL.Text], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([], [UserStats], ['query']),
  'getWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([], [], []),
  'registerWithReferral' : IDL.Func([IDL.Text], [], []),
  'rejectWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'requestWithdrawal' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startReadingSession' : IDL.Func([IDL.Nat], [], []),
  'updateArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserStats = IDL.Record({
    'referralCode' : IDL.Text,
    'coinBalance' : IDL.Int,
    'totalEarned' : IDL.Int,
    'referralCount' : IDL.Int,
    'dailyReadCount' : IDL.Int,
    'lastResetDate' : IDL.Int,
  });
  const Time = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'bankAccountNumber' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'ifscCode' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'upiId' : IDL.Text,
    'bankAccountName' : IDL.Text,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'approveWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimReward' : IDL.Func([], [], []),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats))],
        ['query'],
      ),
    'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
    'getNews' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Article)], ['query']),
    'getReferralCode' : IDL.Func([], [IDL.Text], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([], [UserStats], ['query']),
    'getWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([], [], []),
    'registerWithReferral' : IDL.Func([IDL.Text], [], []),
    'rejectWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'requestWithdrawal' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startReadingSession' : IDL.Func([IDL.Nat], [], []),
    'updateArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };