/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'summary' : string,
  'imageUrl' : string,
  'category' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'referralCode' : string,
  'coinBalance' : bigint,
  'totalEarned' : bigint,
  'referralCount' : bigint,
  'dailyReadCount' : bigint,
  'lastResetDate' : bigint,
}
export interface WithdrawalRequest {
  'id' : bigint,
  'bankAccountNumber' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'ifscCode' : string,
  'note' : string,
  'createdAt' : Time,
  'user' : Principal,
  'upiId' : string,
  'bankAccountName' : string,
  'amount' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArticle' : ActorMethod<[string, string, string, string, string], bigint>,
  'approveWithdrawal' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimReward' : ActorMethod<[], undefined>,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserStats]>>,
  'getArticle' : ActorMethod<[bigint], [] | [Article]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getNews' : ActorMethod<[bigint, bigint], Array<Article>>,
  'getReferralCode' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[], UserStats>,
  'getWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[], undefined>,
  'registerWithReferral' : ActorMethod<[string], undefined>,
  'rejectWithdrawal' : ActorMethod<[bigint, string], undefined>,
  'requestWithdrawal' : ActorMethod<
    [bigint, string, string, string, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startReadingSession' : ActorMethod<[bigint], undefined>,
  'updateArticle' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];